### PR TITLE
Add tests, validate download, include RHEL/CentOS 7 and some more.

### PR DESCRIPTION
**Pull request by furhouse**
This adds rspec-puppet and beaker tests to the module. Besides tests, its a pretty big (~~but no breaking changes afaik~~ with breaking changes due to the new dependency..) overhaul:

- Almost every parameter has been moved to params.pp, so it can be overwritten if required.
- Instead of downloading (and redownloading after a reboot) to `/tmp/`, an archive directory + parent directory is created: `/var/cache/puppet/archives`, which holds the downloaded packages. This adds versioning on disk as well.
- Added a new dependency, https://github.com/lwf/puppet-remote_file, which can be used to verify downloaded files with a checksum. By default, `checksum_type` is set to `sha256`, and is limited to just `md5` and `sha256` (while the [regular checksum types](https://docs.puppet.com/puppet/latest/type.html#file-attribute-checksum) could apply). The `sha256` is pinned in `params.pp`, and matches the version which is currently downloaded by the default parameters of the module. The `sha256`sums should be bumped if the `package_version` changes.
- Added RHEL/CentOS 7 to `metadata.json`.
- Updated the README accordingly.

This would also close both https://github.com/tentwentyfour/puppet-graylog-collector-sidecar/issues/1 and https://github.com/tentwentyfour/puppet-graylog-collector-sidecar/issues/3.

### CODE REVIEW

**Comment by furhouse** [comment]
Oh, it also adds puppet 4 support, although validation should be moved to https://docs.puppet.com/puppet/4.10/lang_data_type.html.

Regarding the rvm version in .travis.yaml, I was having some issues with ruby 2.1.5 (which is the version puppet is tested against afaik) on my desktop, so I've switched to 2.1.8.

**Comment by kwisatz** [comment]
Oh wow, much obliged @furhouse. This is an awesome PR!

I'll try to review and merge this within the day. 

Only one request though: Could you squash your 6 commits into 1 or 2 commits instead? (One for the tests and another one for the download verification/remote_file functionality).

**Comment by furhouse** [comment]
You're welcome!

To be honest, I'm unsure how to rebase and cherry-pick in subsequent PRs, but I wouldn't mind squashing it in a single commit. Is that OK?

**Comment by kwisatz** [comment]
A single commit would be okay as well, yes. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by furhouse** [comment]
Ok, I've pushed to a single commit.

**Comment by kwisatz** [comment]
Thanks. I took a look and here are a few comments and questions:

* You mentioned you had trouble with the 2.1.5 release of ruby. Any particular reasons you removed versions 2.2.x and 2.3.x from the .travis.yml file? Or does the environment matrix handle that now?
* You added a CHANGELOG file, but it contains a sample/template only. Could you add a little changelog for your changes please?
* In class_spec.rb, I think you left some things unchanged from your puppet-oxidized module
* You moved the regexp match of the version string from install.pp to params.pp. Since the values from params.pp are the defaults, overridden by values passed to the module (in init.pp), doesn't this mean the version parts and thus the download URLs will contain "old" data unmodified by whatever is passed to the module? (I would expect params.pp to be interpreted – and thus those variables set – before init.pp)

Other than that, and as much as I can judge from my meager knowledge on testing puppet modules, great job!

**Comment by furhouse** [comment]
Updated:

- There were no tests written, so I figured a single version might be OK to get started... I've added 2.2.6, 2.3.1 and 2.4.0.
- The empty CHANGELOG has been filled.
- Missed that one, fixed.
- True, didn't think of that. Moved the regexp back to install.pp.

I've also updated the parameters in init.pp, and figured I'd prepare them for puppet 4 while I was at it. Should be easy to copy/paste for replacing the class parameters in the future.

**Pull request merged**
